name: Go build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_mac:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - run: GOOS=darwin GOARCH=amd64 go build -v ./...
    - run: chmod +x pinky
    - uses: actions/upload-artifact@v2
      with:
        name: mac-distribution
        path: pinky

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - run: GOOS=linux GOARCH=amd64 go build -v ./...
    - run: chmod +x pinky
    - uses: actions/upload-artifact@v2
      with:
        name: linux-distribution
        path: pinky

  build_wingows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - run: GOOS=windows GOARCH=amd64 go build -v ./...
    - uses: actions/upload-artifact@v2
      with:
        name: windows-distribution
        path: pinky.exe